import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import { useTheme } from '../contexts/ThemeContext'
import i18n, { STORAGE_KEY } from '../i18n'
import { getConversationHistory, getDailySummaries } from '../services/api'

export default function Settings() {
  const { t } = useTranslation()
  const { theme, toggleTheme } = useTheme()
  const [lang, setLang] = useState(i18n.language || 'es')

  // FIX 10: daily reminder state
  const [reminderEnabled, setReminderEnabled] = useState(() => {
    try {
      const stored = JSON.parse(localStorage.getItem('breso_daily_reminder') || '{}')
      return stored.enabled || false
    } catch { return false }
  })
  const [reminderTime, setReminderTime] = useState(() => {
    try {
      const stored = JSON.parse(localStorage.getItem('breso_daily_reminder') || '{}')
      return stored.time || '20:00'
    } catch { return '20:00' }
  })

  const [exportMsg, setExportMsg] = useState(false)

  const exportAsPDF = (data, type) => {
    const currentLang = i18n.language || 'es'
    const pdfContent = {
      es: {
        title: 'Mi historial en BRESO',
        name: 'Nombre',
        plan: 'Plan activo',
        exported: 'Exportado el',
        dayHistory: 'Historial por día',
        conversations: 'Conversaciones recientes',
        noSummaries: 'Sin resúmenes disponibles.',
        noConversations: 'Sin conversaciones registradas.',
        me: 'Yo',
        disclaimer: 'Generado por Soledad — BRESO',
        professionalTitle: 'Informe de bienestar — BRESO',
        professionalSubtitle: 'Generado por Soledad para uso profesional',
        patient: 'Paciente',
        anonymous: 'Anónimo',
        period: 'Período',
        periodValue: 'Últimos 30 días',
        checkins: 'Check-ins realizados',
        summary: 'Resumen',
        summaryValue: 'El paciente ha mantenido check-ins regulares durante el período evaluado.',
        alerts: 'Alertas registradas',
        clinicalNote: 'Este informe no constituye un diagnóstico clínico.',
      },
      en: {
        title: 'My BRESO History',
        name: 'Name',
        plan: 'Active plan',
        exported: 'Exported on',
        dayHistory: 'Daily history',
        conversations: 'Recent conversations',
        noSummaries: 'No summaries available.',
        noConversations: 'No conversations recorded.',
        me: 'Me',
        disclaimer: 'Generated by Soledad — BRESO',
        professionalTitle: 'Wellness Report — BRESO',
        professionalSubtitle: 'Generated by Soledad for professional use',
        patient: 'Patient',
        anonymous: 'Anonymous',
        period: 'Period',
        periodValue: 'Last 30 days',
        checkins: 'Check-ins completed',
        summary: 'Summary',
        summaryValue: 'The patient has maintained regular check-ins during the evaluated period.',
        alerts: 'Alerts recorded',
        clinicalNote: 'This report does not constitute a clinical diagnosis.',
      },
    }
    const c = pdfContent[currentLang] || pdfContent.es

    const conversaciones = type === 'personal' ? data.conversaciones || [] : []
    const summaries = type === 'personal' ? data.summaries || [] : []
    const content = type === 'personal' ? `
      <html>
      <head>
        <style>
          body { font-family: Inter, sans-serif; padding: 40px; color: #2D2D2D; }
          h1 { color: #7C9A7E; font-weight: 400; }
          h2 { color: #2D2D2D; font-weight: 500; margin-top: 24px; }
          .label { color: #6B7280; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; margin-top: 12px; }
          .value { font-size: 16px; margin-bottom: 8px; }
          .message { border-left: 3px solid #7C9A7E; padding: 8px 16px; margin: 8px 0; border-radius: 0 8px 8px 0; }
          .soledad { background: #F0F7F0; }
          .user { background: #FAFAFA; }
          .day-row { display: flex; gap: 16px; padding: 8px 0; border-bottom: 1px solid #F3F4F6; font-size: 14px; }
          .day-date { color: #6B7280; min-width: 100px; }
          .day-summary { color: #2D2D2D; flex: 1; }
          hr { border: none; border-top: 1px solid #E5E7EB; margin: 20px 0; }
        </style>
      </head>
      <body>
        <h1>🌱 ${c.title}</h1>
        <div class="label">${c.name}</div>
        <div class="value">${data.nombre || '—'}</div>
        <div class="label">${c.plan}</div>
        <div class="value">${data.plan || '—'}</div>
        <div class="label">${c.exported}</div>
        <div class="value">${new Date().toLocaleDateString(currentLang === 'en' ? 'en-US' : 'es-AR')}</div>
        <hr/>
        <h2>${c.dayHistory}</h2>
        ${summaries.length === 0
          ? `<p style="color:#9CA3AF">${c.noSummaries}</p>`
          : summaries.map(s => `
            <div class="day-row">
              <span class="day-date">${s.date}</span>
              <span class="day-summary">${s.summary}</span>
            </div>
          `).join('')}
        <hr/>
        <h2>${c.conversations}</h2>
        ${conversaciones.length === 0 ? `<p style="color:#9CA3AF">${c.noConversations}</p>` : conversaciones.map(m => `
          <div class="message ${m.role === 'soledad' || m.from === 'breso' ? 'soledad' : 'user'}">
            <strong>${m.role === 'soledad' || m.from === 'breso' ? 'Soledad' : c.me}</strong>
            <p style="margin:4px 0">${m.text || ''}</p>
          </div>
        `).join('')}
        <hr/>
        <p style="color:#9CA3AF;font-size:12px;">${c.disclaimer}</p>
      </body>
      </html>
    ` : `
      <html>
      <head>
        <style>
          body { font-family: Inter, sans-serif; padding: 40px; color: #2D2D2D; }
          h1 { color: #7C9A7E; font-weight: 400; }
          .label { color: #6B7280; font-size: 12px; text-transform: uppercase; letter-spacing: 0.05em; margin-top: 12px; }
          .value { font-size: 16px; margin-bottom: 8px; }
          hr { border: none; border-top: 1px solid #E5E7EB; margin: 20px 0; }
        </style>
      </head>
      <body>
        <h1>🌱 ${c.professionalTitle}</h1>
        <p><em>${c.professionalSubtitle}</em></p>
        <div class="label">${c.patient}</div>
        <div class="value">${c.anonymous}</div>
        <div class="label">${c.period}</div>
        <div class="value">${c.periodValue}</div>
        <div class="label">${c.checkins}</div>
        <div class="value">${data.dias_racha || 0} ${currentLang === 'en' ? 'streak days' : 'días de racha'}</div>
        <div class="label">${c.summary}</div>
        <div class="value">${c.summaryValue}</div>
        <div class="label">${c.alerts}</div>
        <div class="value">0</div>
        <hr/>
        <p style="color: #9CA3AF; font-size: 12px;">${c.disclaimer}. ${c.clinicalNote}</p>
      </body>
      </html>
    `
    const printWindow = window.open('', '_blank')
    printWindow.document.write(content)
    printWindow.document.close()
    printWindow.print()
  }

  const handleLangChange = (e) => {
    const l = e.target.value
    setLang(l)
    try { localStorage.setItem(STORAGE_KEY, l) } catch {}
    i18n.changeLanguage(l)
  }

  // FIX 10: toggle reminder + request notification permission
  const handleReminderToggle = async () => {
    const newEnabled = !reminderEnabled
    if (newEnabled && 'Notification' in window) {
      const perm = await Notification.requestPermission()
      if (perm !== 'granted') return
    }
    setReminderEnabled(newEnabled)
    try {
      localStorage.setItem('breso_daily_reminder', JSON.stringify({ enabled: newEnabled, time: reminderTime }))
    } catch {}
  }

  const handleReminderTimeChange = (e) => {
    const val = e.target.value
    setReminderTime(val)
    try {
      const stored = JSON.parse(localStorage.getItem('breso_daily_reminder') || '{}')
      localStorage.setItem('breso_daily_reminder', JSON.stringify({ ...stored, time: val }))
    } catch {}
  }

  const handleExportPersonal = async () => {
    const conversaciones = (() => {
      try { return JSON.parse(localStorage.getItem('breso_conversation') || localStorage.getItem('breso_conversation_history') || '[]') } catch { return [] }
    })()
    const data = {
      nombre: localStorage.getItem('breso_user_name') || null,
      plan: localStorage.getItem('breso_selected_plan') || null,
      dias_racha: null,
      conversaciones,
      summaries: [],
    }
    try {
      const res = await getConversationHistory(200)
      const items = res.data?.messages || res.messages || []
      if (items.length > 0) {
        data.conversaciones = items
      }
    } catch {}
    try {
      const summaryRes = await getDailySummaries()
      const summaryItems = Array.isArray(summaryRes.data) ? summaryRes.data : (Array.isArray(summaryRes) ? summaryRes : [])
      if (summaryItems.length > 0) data.summaries = summaryItems
    } catch {}
    exportAsPDF(data, 'personal')
    setExportMsg(true)
    setTimeout(() => setExportMsg(false), 3000)
  }

  const handleExportProfessional = () => {
    const data = { dias_racha: null }
    exportAsPDF(data, 'professional')
    setExportMsg(true)
    setTimeout(() => setExportMsg(false), 3000)
  }

  const handleDelete = () => {
    const input = window.prompt(t('settings.delete_confirm'))
    if (input === 'ELIMINAR') {
      alert('Account marked for deletion')
    }
  }

  return (
    <div className="animate-fade-in-page space-y-6">
      <h1 className="text-2xl font-bold text-textdark dark:text-dm-text">
        {t('settings.title')}
      </h1>

      <div className="space-y-6">

        {/* Preferences */}
        <div className="bg-white dark:bg-dm-surface rounded-2xl p-6 shadow-soft space-y-5">
          {/* Theme */}
          <div className="flex items-center justify-between">
            <div>
              <p className="font-medium text-textdark dark:text-dm-text">{t('settings.theme')}</p>
              <p className="text-xs text-textdark/60 dark:text-dm-muted">
                {theme === 'dark' ? t('nav.darkModeLabel') : t('nav.lightModeLabel')}
              </p>
            </div>
            <button
              type="button"
              onClick={toggleTheme}
              className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${theme === 'dark' ? 'bg-sage' : 'bg-softgray dark:bg-dm-border'}`}
            >
              <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${theme === 'dark' ? 'translate-x-6' : 'translate-x-1'}`} />
            </button>
          </div>

          <hr className="border-softgray dark:border-dm-border" />

          {/* Language */}
          <div className="flex items-center justify-between">
            <p className="font-medium text-textdark dark:text-dm-text">{t('settings.language')}</p>
            <select
              value={lang}
              onChange={handleLangChange}
              className="bg-transparent text-sm font-medium text-sage outline-none cursor-pointer"
            >
              <option value="es">Español</option>
              <option value="en">English</option>
            </select>
          </div>

          <hr className="border-softgray dark:border-dm-border" />

          {/* Daily reminder toggle */}
          <div className="flex items-center justify-between">
            <div>
              <p className="font-medium text-textdark dark:text-dm-text">{t('settings.reminder')}</p>
              <p className="text-xs text-textdark/60 dark:text-dm-muted mt-0.5">
                {t('settings.reminder_text')} {reminderTime}
              </p>
            </div>
            <div className="flex items-center gap-3">
              {reminderEnabled && (
                <input
                  type="time"
                  value={reminderTime}
                  onChange={handleReminderTimeChange}
                  className="bg-transparent text-sm font-medium text-sage outline-none cursor-pointer"
                />
              )}
              <button
                type="button"
                onClick={handleReminderToggle}
                className={`relative inline-flex h-6 w-11 items-center rounded-full transition-colors ${reminderEnabled ? 'bg-sage' : 'bg-softgray dark:bg-dm-border'}`}
              >
                <span className={`inline-block h-4 w-4 transform rounded-full bg-white transition-transform ${reminderEnabled ? 'translate-x-6' : 'translate-x-1'}`} />
              </button>
            </div>
          </div>
        </div>
        {/* Export Data */}
        <div className="bg-white dark:bg-dm-surface rounded-2xl p-6 shadow-soft space-y-4">
          <div>
            <p className="font-medium text-textdark dark:text-dm-text mb-3">{t('settings.export_title')}</p>
            <div className="flex gap-3">
              <button
                type="button"
                onClick={handleExportPersonal}
                className="flex-1 rounded-xl border-2 border-sage text-sage text-sm font-semibold py-2.5 hover:bg-sage hover:text-white transition-colors"
              >
                {t('settings.export_personal')}
              </button>
              <button
                type="button"
                onClick={handleExportProfessional}
                className="flex-1 rounded-xl border-2 border-textdark/20 dark:border-dm-border text-textdark/70 dark:text-dm-muted text-sm font-semibold py-2.5 hover:border-textdark/40 dark:hover:border-dm-muted transition-colors"
              >
                {t('settings.export_professional')}
              </button>
            </div>
            {exportMsg && <p className="text-xs text-sage font-medium mt-3">{t('settings.exportSuccess')}</p>}
          </div>
        </div>

        {/* Delete Account */}
        <div className="pt-2 pb-6 flex justify-center">
          <button
            type="button"
            onClick={handleDelete}
            className="text-xs font-semibold text-red-500 hover:text-red-700 transition-colors"
          >
            {t('settings.delete_account')}
          </button>
        </div>

      </div>
    </div>
  )
}
